language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-26
  before_install:
    - yes | sdkmanager "platforms;android-26"
  script:
    - ./gradlew build connectedCheck
