language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
  before_install:
    - yes | sdkmanager "platforms;android-26"
    - yes | sdkmanager "build-tools;27.0.3"
